[package]
name = "fishnet"
version = "2.3.5"
description = "Distributed Stockfish analysis for lichess.org"
repository = "https://github.com/niklasf/fishnet"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["command-line-utilities", "web-programming::http-client", "games"]
keywords = ["chess", "lichess"]
edition = "2018"
exclude = [
    "Stockfish/**/*.o",
    "Stockfish/**/*.s",
    "Stockfish/**/.depend",
    "Stockfish/**/*.nnue",
    "Fairy-Stockfish/**/*.o",
    "Fairy-Stockfish/**/*.s",
    "Fairy-Stockfish/**/.depend",
    "Fairy-Stockfish/**/*.nnue",
]

[dependencies]
arrayvec = "0.7"
atty = "0.2"
auditable = "0.1"
bitflags = "1"
clap = "3.0.0-beta.4"
configparser = "2"
xz2 = "0.1"
num_cpus = "1"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
rustls = "0.19" # will fail at runtime if mismatch with reqwest
self_update = { version = "0.27", features = ["rustls"], default-features = false }
serde = "1"
serde_json = "1"
serde_with = "1"
home = "0.5"
shakmaty = { version = "0.19", features = ["variant"] }
shell-escape = "0.1"
tempfile = "3"
tokio = { version = "1", features = ["rt", "macros", "sync", "time", "signal", "process", "io-util"], default-features = false }
url = "2"
serde_repr = "0.1"
webpki-roots = "0.21"
thousands = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "10"

[build-dependencies]
auditable-build = "0.1"
glob = "0.3"
xz2 = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
